os:
  - linux
sudo: false
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lib32stdc++6
      - fonts-droid-fallback
before_script:
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter packages get
  - ./flutter/bin/flutter test
cache:
  directories:
    - flutter
    - $HOME/.pub-cache
