os:
  - linux
sudo: false
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lib32stdc++6
      - fonts-droid-fallback
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - git clone https://github.com/Sreyas-108/lg_controller.git
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter packages get
  - ./flutter/bin/flutter test
cache:
  directories:
#    - flutter			# If flutter folder is removed from cache, please add   "- git clone https://github.com/flutter/flutter.git -b beta" in before_scripts.
    - $HOME/.pub-cache
